export type Project = {
  slug: string;
  src: string;
  gallery: string[];
  title: string;
  category: string;
  desc: string;
  year: string;
  location: string;
  area: string;
  scope: string[];
};

export const projects: Project[] = [
  {
    slug: "residential-interior-i",
    src: "/projects/residentail interior 1.2.png",
    gallery: [
      "/projects/residentail interior 1.2.png",
      "/projects/residentail interior 1.3.jpg",
      "/projects/residentail interior 1.4.jpg",
    ],
    title: "Residential Interior I",
    category: "Interior",
    desc: "A contemporary residential interior blending warm textures with modern spatial planning. Every surface tells a story — from hand-selected stone to bespoke timber joinery.",
    year: "2024",
    location: "Pune, India",
    area: "2,400 sq ft",
    scope: ["Space Planning", "Interior Design", "Furniture Selection", "Lighting Design"],
  },
  {
    slug: "residential-interior-ii",
    src: "/projects/residentail interior 1.3.jpg",
    gallery: [
      "/projects/residentail interior 1.3.jpg",
      "/projects/residentail interior 1.5.jpg",
      "/projects/residentail interior 1.6.jpg",
    ],
    title: "Residential Interior II",
    category: "Interior",
    desc: "Curated lighting and natural materials come together in this intimate living space. The design language draws on the owners' love of travel and artisan craft.",
    year: "2023",
    location: "Mumbai, India",
    area: "1,800 sq ft",
    scope: ["Interior Design", "Custom Joinery", "Material Specification"],
  },
  {
    slug: "residential-interior-iii",
    src: "/projects/residentail interior 1.4.jpg",
    gallery: [
      "/projects/residentail interior 1.4.jpg",
      "/projects/residentail interior 1.7.jpg",
      "/projects/residentail interior 1.8.jpg",
    ],
    title: "Residential Interior III",
    category: "Interior",
    desc: "Open-plan design with elegant finishes for a young urban family. The brief called for a home that could grow with the family — flexible, functional, and beautiful.",
    year: "2024",
    location: "Ahmedabad, India",
    area: "3,100 sq ft",
    scope: ["Architecture", "Interior Design", "Landscape Coordination"],
  },
  {
    slug: "residential-interior-iv",
    src: "/projects/residentail interior 1.5.jpg",
    gallery: [
      "/projects/residentail interior 1.5.jpg",
      "/projects/residentail interior 1.9.jpg",
      "/projects/residentail interior 1.6.jpg",
    ],
    title: "Residential Interior IV",
    category: "Interior",
    desc: "A serene bedroom suite with bespoke joinery and layered neutral tones. Designed as a sanctuary, this project prioritised calm, comfort and quiet luxury.",
    year: "2023",
    location: "Surat, India",
    area: "950 sq ft",
    scope: ["Interior Design", "Custom Furniture", "Lighting"],
  },
  {
    slug: "residential-interior-v",
    src: "/projects/residentail interior 1.6.jpg",
    gallery: [
      "/projects/residentail interior 1.6.jpg",
      "/projects/residentail interior 1.7.jpg",
      "/projects/residentail interior 1.4.jpg",
    ],
    title: "Residential Interior V",
    category: "Interior",
    desc: "Kitchen and dining area reimagined for effortless entertaining. A seamless connection between cooking, dining and living was the defining brief.",
    year: "2024",
    location: "Vadodara, India",
    area: "1,200 sq ft",
    scope: ["Interior Design", "Kitchen Planning", "Material Curation"],
  },
  {
    slug: "residential-interior-vi",
    src: "/projects/residentail interior 1.7.jpg",
    gallery: [
      "/projects/residentail interior 1.7.jpg",
      "/projects/residentail interior 1.8.jpg",
      "/projects/residentail interior 1.9.jpg",
    ],
    title: "Residential Interior VI",
    category: "Interior",
    desc: "Compact yet luxurious, every square foot of this apartment is thoughtfully designed. A masterclass in making smaller spaces feel expansive and refined.",
    year: "2023",
    location: "Nashik, India",
    area: "800 sq ft",
    scope: ["Interior Design", "Space Optimisation", "Joinery Design"],
  },
  {
    slug: "residential-interior-vii",
    src: "/projects/residentail interior 1.8.jpg",
    gallery: [
      "/projects/residentail interior 1.8.jpg",
      "/projects/residentail interior 1.2.png",
      "/projects/residentail interior 1.3.jpg",
    ],
    title: "Residential Interior VII",
    category: "Interior",
    desc: "Timeless interiors with handcrafted details that honour Indian craft traditions. Working with local artisans, we created surfaces and objects that cannot be replicated.",
    year: "2022",
    location: "Rajkot, India",
    area: "2,800 sq ft",
    scope: ["Interior Design", "Artisan Coordination", "Custom Fixtures"],
  },
  {
    slug: "residential-interior-viii",
    src: "/projects/residentail interior 1.9.jpg",
    gallery: [
      "/projects/residentail interior 1.9.jpg",
      "/projects/residentail interior 1.5.jpg",
      "/projects/residentail interior 1.7.jpg",
    ],
    title: "Residential Interior VIII",
    category: "Interior",
    desc: "Monochromatic palette with rich tactile surfaces and curated art. The architecture recedes to let the objects and light take centre stage.",
    year: "2024",
    location: "Pune, India",
    area: "1,600 sq ft",
    scope: ["Interior Design", "Art Curation", "Lighting Design"],
  },
  {
    slug: "residential-project-2a",
    src: "/projects/residentail project 2.1.jpg",
    gallery: [
      "/projects/residentail project 2.1.jpg",
      "/projects/residentail project 2.2.jpg",
      "/projects/residentail project 2.jpg",
    ],
    title: "Residential Project 2-A",
    category: "Architecture",
    desc: "Exterior architecture with clean volumes and a considered relationship with its landscape. The building is designed to minimise solar heat gain while maximising cross ventilation.",
    year: "2023",
    location: "Pune, India",
    area: "4,500 sq ft",
    scope: ["Architecture", "Site Planning", "Structural Design", "Interior"],
  },
  {
    slug: "residential-project-2b",
    src: "/projects/residentail project 2.2.jpg",
    gallery: [
      "/projects/residentail project 2.2.jpg",
      "/projects/residentail project 2.1.jpg",
      "/projects/rsidentail project.jpg",
    ],
    title: "Residential Project 2-B",
    category: "Architecture",
    desc: "Facade detailing that merges traditional motifs with contemporary geometry. A layered skin that creates shade, pattern and identity simultaneously.",
    year: "2024",
    location: "Mumbai, India",
    area: "3,800 sq ft",
    scope: ["Architecture", "Facade Design", "Interior Design"],
  },
  {
    slug: "residential-project-ii",
    src: "/projects/residentail project 2.jpg",
    gallery: [
      "/projects/residentail project 2.jpg",
      "/projects/residentail project 2.1.jpg",
      "/projects/residentail project 2.2.jpg",
    ],
    title: "Residential Project II",
    category: "Architecture",
    desc: "A complete residential development with thoughtful site planning and landscaping. The masterplan creates strong public-private boundaries while connecting to the wider neighbourhood.",
    year: "2022",
    location: "Ahmedabad, India",
    area: "8,000 sq ft",
    scope: ["Master Planning", "Architecture", "Landscape", "Interior Design"],
  },
  {
    slug: "residential-project",
    src: "/projects/rsidentail project.jpg",
    gallery: [
      "/projects/rsidentail project.jpg",
      "/projects/residentail project 2.jpg",
      "/projects/residentail interior 1.2.png",
    ],
    title: "Residential Project",
    category: "Architecture",
    desc: "A family home designed around natural ventilation, light, and indoor-outdoor living. Inspired by the traditional Indian courtyard house, adapted for contemporary life.",
    year: "2023",
    location: "Surat, India",
    area: "5,200 sq ft",
    scope: ["Architecture", "Landscape", "Interior Design", "Vastu Consultation"],
  },
];